require 'active_record'
require 'active_record/base'

require 'models/error'
require 'models/consumable'
require 'models/base'
require 'models/ticket'
require 'models/login_ticket'
require 'models/service_ticket'
require 'models/proxy_ticket'
require 'models/proxy_granting_ticket'
require 'models/ticket_granting_ticket'
